server:
  servlet:
    context-path: /java-cloud/v1
spring:
  profiles:
    active: amazon-rds
  datasource:
    url: jdbc:mysql://localhost:3306/java_cloud?useTimezone=true&serverTimezone=UTC
    username: root
    password: ep25dbbr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true

---

spring:
  profiles: amazon-rds
  datasource:
    url: jdbc:mysql://database-1.cnteopdpllko.us-east-1.rds.amazonaws.com:3306/java_cloud?useTimezone=true&serverTimezone=UTC
    username: admin
    password: ep25dbbr